/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testingRando(){
        Library sut = new Library();
        int randomNumberResult = sut.rando();
        assertTrue(randomNumberResult < 7);
        assertTrue(randomNumberResult > 0);

    }
    @Test void testingContainsDuplicate(){
        Library sut = new Library();
        int[] arr = new int[]{1,2,3,3,5,6};
        boolean duplicateChecker = sut.containsDuplicates(arr);
        assertTrue(duplicateChecker);

    }
    @Test void noDuplicates(){
        Library sut = new Library();
        int[] arr = new int[]{1,2,3,4,5,6};
        boolean duplicateChecker = sut.containsDuplicates(arr);
        assertFalse(duplicateChecker);
    }
    @Test void averageInTheArrayChecker(){
        Library sut = new Library();
        int[] arr = new int[]{2,4,6};
        int calculatingAverages = sut.calculatingAverages(arr);
        assertEquals(4, sut.calculatingAverages(arr));

    }
    @Test public void arrayOfArrays(){
        Library sut = new Library();
        int[][] randomNumbers = {
                {54, 55, 56, 67, 90, 10, 25},
                {91, 99, 300, 400, 20, 1, 19},
                {100, 200, 300, 400, 500, 600, 700},
                {1, 2, 3, 4, 5, 6, 7}
        };
        assertEquals(randomNumbers[3], sut.arrayOfArrays(randomNumbers));
        System.out.println(randomNumbers[3]);
    }

}
