/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Restaurant {
    public String restaurantName;
    public int starRating;

     public Restaurant(String restaurantName, int starRating){
        this.restaurantName = restaurantName;
        this.starRating = starRating;

    }

    public boolean someLibraryMethod() {
        return false;
    }
}
